"""Report Generator: 生成 Markdown 诊断报告."""
from datetime import datetime
from pathlib import Path
from src.models import RCAOutput, StructuredEvidence


def generate_report(rca: RCAOutput, evidence: StructuredEvidence,
                    output_path: str = "report.md") -> str:
    """根据 RCA 结果和原始证据生成 Markdown 报告。

    返回报告文件路径。
    """
    analysis_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 数据质量
    quality_display = {
        "HIGH": "HIGH（数据充分，结论可信度高）",
        "MEDIUM": "MEDIUM（数据基本可用，结论需谨慎验证）",
        "LOW": "LOW（数据严重缺失，结论仅供参考）",
    }.get(evidence.data_quality, evidence.data_quality)

    # Timeline
    if rca.timeline:
        timeline_str = "\n".join(f"- {t}" for t in rca.timeline)
    else:
        timeline_str = "_无时间线数据_"

    # Evidence
    if rca.evidence:
        evidence_str = "\n".join(f"1. {e}" for e in rca.evidence)
    else:
        evidence_str = "_无详细证据_"

    # Alternative Hypotheses
    if rca.alternative_hypotheses:
        alt_str = "\n".join(f"- {h}" for h in rca.alternative_hypotheses)
    else:
        alt_str = "_未列出竞争性假设_"

    # Recommendations
    if rca.recommendations:
        rec_str = "\n".join(f"{i+1}. {r}" for i, r in enumerate(rca.recommendations))
    else:
        rec_str = "_暂无修复建议_"

    report = f"""# Root Cause Analysis Report

**分析时间**: {analysis_time}
**故障时间**: {evidence.fault_time}
**数据质量**: {quality_display}

---

## Summary

{rca.summary}

---

## Root Cause

{rca.root_cause}

---

## Impact

{rca.impact or '_未评估影响范围_'}

---

## Timeline

{timeline_str}

---

## Evidence

{evidence_str}

---

## Alternative Hypotheses Considered

{alt_str}

---

## Recommendations

{rec_str}

---

*Report generated by SOSReport RCA Engine V0.2*
"""

    output = Path(output_path)
    output.write_text(report, encoding="utf-8")
    return str(output.resolve())
